version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:17
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./dist

  deploy:
    working_directory: ~/app
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/app
      - run: ssh -o "StrictHostKeyChecking no" -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} "rm -rf ~/website/dist/assets"
      - run: scp -o "StrictHostKeyChecking no" -P ${SSH_PORT} -r dist ${SSH_USER}@${SSH_HOST}:website

workflows:
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
