version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:18
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install -g pnpm
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Build website
          command: pnpm build
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./dist
  deploy:
    working_directory: ~/app
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Remove old assets
          command: ssh -o "StrictHostKeyChecking no" -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} "rm -rfv ~/website/dist/assets"
      - run:
          name: Copy new build to server
          command: scp -o "StrictHostKeyChecking no" -P ${SSH_PORT} -r dist ${SSH_USER}@${SSH_HOST}:website

workflows:
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
